// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'src/pollModule/persistence/schema.prisma',
    migrations: {
        path: 'src/pollModule/persistence/migrations',
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
});
